modLoader="javafml"
loaderVersion="[0,)"
license="${mod_license}"
issueTrackerURL="https://github.com/Volwert123/more-food/issues"

[[mods]]
    modId="${mod_id}"
    version="${mod_version}"
    displayName="${mod_name}"
    updateJSONURL="https://api.modrinth.com/updates/more-food-xd/forge_updates.json?neoforge=only"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/more-food-xd"
    logoFile="${mod_icon}"
    authors="${mod_author}"
    description='''${mod_description}'''

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[${neoforge_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="[${minecraft_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="balm"
    type="required"
    versionRange="[${balm_version},)"
    ordering="NONE"
    side="BOTH"